version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804
install:
- cmd: cinst innosetup
- sh: sudo apt-get -y update && sudo apt-get install -y libcurl4-openssl-dev pkg-config libtbb-dev libasound2-dev libgtk-3-dev libglew-dev
- git submodule update --init --recursive
environment:
  matrix:
  - {}
build_script:
- cmd: 
    cmake -S . -B builds -G "Visual Studio 15 2017 Win64" 
    cmake --build builds
- sh: >-
    cmake -S . -B builds &&
    cmake -S . -B builds/Debug -DCMAKE_BUILD_TYPE=DEBUG &&
    cmake --build builds/Debug && 
    cmake -S . -B builds/Release -DCMAKE_BUILD_TYPE=RELEASE &&
    cmake --build builds/Release
