# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Windows BCR2000 Master

on: push

jobs:
  build-windows:
      runs-on: windows-2019
      steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v2        
        with:
          fetch-depth: 0

      - name: Additionally checkout submodules - don't use checkout action as it will overwrite refs
        run: |
          git submodule update --recursive --init --depth 1

      - name: Install NuGet
        uses: nuget/setup-nuget@v1        
        with:
          nuget-version: latest

      - name: Install Innosetup with NuGet
        run: nuget install Tools.InnoSetup

      - name: CMake configure
        shell: bash
        # -DCMAKE_SYSTEM_VERSION=10.0.19041.0
        run: |
          cmake -S . -B builds -G "Visual Studio 15 2017 Win64"  

      - name: CMake build
        run: |
          cmake --build builds --config Debug
          cmake --build builds --config Release

